version: '3.5'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "0.0.0.0"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - banco-de-dados:/var/lib/mysql

volumes:
    banco-de-dados: